/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DSC.JROficina.Apresentacao;

import DSC.JROficina.Aplicacao.Fornecedor;
import DSC.JROficina.Aplicacao.Peca;
import DSC.JROficina.Aplicacao.Repositorio;
import DSC.JROficina.Persistencia.PecaDAO;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigo
 */
public class AdcPeca extends TelaBusca<Peca> {

    public AdcPeca(Repositorio<Peca> repositorio, Class tipo_tela) {
        super(repositorio, tipo_tela);
        initComponents();
        filtro = new Peca();
        this.repositorio = repositorio;
        this.tipo_tela = tipo_tela;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusca = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        btnBusca = new javax.swing.JButton();
        BtnAdcPeca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtQtde = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setText("Nome:");

        tblBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblBusca);

        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        BtnAdcPeca.setText("Adicionar Peça");
        BtnAdcPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdcPecaActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBusca))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(BtnAdcPeca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusca))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnAdcPeca)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void BtnAdcPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdcPecaActionPerformed
        
    }//GEN-LAST:event_BtnAdcPecaActionPerformed
      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdcPeca;
    private javax.swing.JButton btnBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBusca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQtde;
    // End of variables declaration//GEN-END:variables
   
    
    public Peca adcPeca(){
        int x = retornaIdSelecionado();
        Peca p = new Peca();
        PecaDAO pp = null;
        p = pp.Abrir(x);
        p.setQtde(Integer.valueOf(txtQtde.getText()));
        
        return p;
    }

    @Override
    public int retornaIdSelecionado() {
       int linha = tblBusca.getSelectedRow();
       int id = Integer.parseInt(tblBusca.getModel().getValueAt(linha,0).toString());
       return id;
    }

    @Override
    public void preencheFiltro() {
        if(!txtNome.getText().isEmpty())
            filtro.setNome(txtNome.getText());
    }

    @Override
    public void preencheTabela(List<Peca> listagem) {
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("Nome");    
        modelo.addColumn("Descrição");
        modelo.addColumn("Estoque");
        modelo.addColumn("Valor Unitario");
        modelo.addColumn("Marca");
        
         for(Peca c : listagem){
            Vector linha = new Vector();
            linha.add(c.getId());
            linha.add(c.getNome());
            linha.add(c.getDesc());
            linha.add(c.getQtde());
            linha.add(c.getValor_venda());
            linha.add(c.getMarca());
            
            modelo.addRow(linha);
            
        }    
        tblBusca.setModel(modelo);
    }

    @Override
    public void limpaFiltro() {
        filtro.setNome(null);
        filtro.setId(0);
        filtro.setDesc(null);
        filtro.setQtde(-1);
        filtro.setValor_compra(-1);
        filtro.setValor_venda(-1);
        filtro.setFornecedor(null);
        filtro.setMarca(null);
    }
    
    
    
    
    
    
    
    
}
