/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DSC.JROficina.Apresentacao;

/**
 *
 * @author Rodrigo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        MnuFornecedores = new javax.swing.JMenuItem();
        mnuUsuario = new javax.swing.JMenuItem();
        mnuPecas = new javax.swing.JMenuItem();
        mnuMotos = new javax.swing.JMenuItem();
        mnuCompras = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        mnuCadastro.setText("Cadastros");
        mnuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroActionPerformed(evt);
            }
        });

        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuClientes);

        MnuFornecedores.setText("Fornecedores");
        MnuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuFornecedoresActionPerformed(evt);
            }
        });
        mnuCadastro.add(MnuFornecedores);

        mnuUsuario.setText("Usuarios");
        mnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuUsuario);

        mnuPecas.setText("Peças");
        mnuPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPecasActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuPecas);

        mnuMotos.setText("Motos");
        mnuMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMotosActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuMotos);

        mnuCompras.setText("Compras");
        mnuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuComprasActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCompras);

        jMenuBar1.add(mnuCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
       ClienteBuscar tela = new ClienteBuscar(Repositorios.getClienteRepositorio(), ClienteEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroActionPerformed
        ClienteBuscar tela = new ClienteBuscar(Repositorios.getClienteRepositorio(), ClienteEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuCadastroActionPerformed

    private void MnuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuFornecedoresActionPerformed
        FornecedorBuscar tela = new FornecedorBuscar(Repositorios.getFornecedorRepositorio(), FornecedorEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_MnuFornecedoresActionPerformed

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        UsuarioBuscar tela = new UsuarioBuscar(Repositorios.getUsuarioRepositorio(), UsuarioEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    private void mnuPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPecasActionPerformed
      PecaBuscar tela = new PecaBuscar(Repositorios.getPecaRepositorio(), PecaEditar.class);
        
        this.add(tela);
        tela.setVisible(true);  
    }//GEN-LAST:event_mnuPecasActionPerformed

    private void mnuMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMotosActionPerformed
       MotoBuscar tela = new MotoBuscar(Repositorios.getMotoRepositorio(), MotoEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuMotosActionPerformed

    private void mnuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuComprasActionPerformed
       CompraBuscar tela = new CompraBuscar(Repositorios.getCompraRepositorio(), CompraEditar.class);
        
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuFornecedores;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuCompras;
    private javax.swing.JMenuItem mnuMotos;
    private javax.swing.JMenuItem mnuPecas;
    private javax.swing.JMenuItem mnuUsuario;
    // End of variables declaration//GEN-END:variables
}
